CATEGORIES = {

    "clams_ru": {
        "Subject-Verb Agreement": [
            "long_vp_coord",
            "obj_rel_across_anim",
            "obj_rel_within_anim",
            "prep_anim",
            "simple_agrmt",
            "subj_rel",
            "vp_coord",
        ],
    },
            
    "blimp": {
        "anaphor_agreement": [
            "anaphor_number_agreement",
            "anaphor_gender_agreement",
        ],
        "argument_structure": [
            "animate_subject_passive",
            "animate_subject_trans",
            "causative",
            "drop_argument",
            "inchoative",
            "intransitive",
            "passive_1",
            "passive_2",
            "transitive",
        ],
        "binding": [
            "principle_A_c_command",
            "principle_A_case_1",
            "principle_A_case_2",
            "principle_A_domain_1",
            "principle_A_domain_2",
            "principle_A_domain_3",
            "principle_A_reconstruction",
        ],
        "control_raising": [
            "existential_there_object_raising",
            "existential_there_subject_raising",
            "expletive_it_object_raising",
            "tough_vs_raising_1",
            "tough_vs_raising_2",
        ],
        "determiner_noun_agreement": [
            "determiner_noun_agreement_1",
            "determiner_noun_agreement_2",
            "determiner_noun_agreement_irregular_1",
            "determiner_noun_agreement_irregular_2",
            "determiner_noun_agreement_with_adjective_1",
            "determiner_noun_agreement_with_adj_2",
            "determiner_noun_agreement_with_adj_irregular_1",
            "determiner_noun_agreement_with_adj_irregular_2",
        ],
        "ellipsis": [
            "ellipsis_n_bar_1",
            "ellipsis_n_bar_2",
        ],
        "irregular_forms": [
            "irregular_past_participle_adjectives",
            "irregular_past_participle_verbs",
        ],
        "island_effects": [
            "adjunct_island",
            "complex_NP_island",
            "coordinate_structure_constraint_complex_left_branch",
            "coordinate_structure_constraint_object_extraction",
            "left_branch_island_echo_question",
            "left_branch_island_simple_question",
            "sentential_subject_island",
            "wh_island", 
        ],
        "npi_licensing": [
            "matrix_question_npi_licensor_present",
            "npi_present_1",
            "npi_present_2",
            "only_npi_licensor_present",
            "only_npi_scope",
            "sentential_negation_npi_licensor_present",
            "sentential_negation_npi_scope",
        ],
        "filler_gap": [
            "wh_questions_object_gap",
            "wh_questions_subject_gap",
            "wh_questions_subject_gap_long_distance",
            "wh_vs_that_no_gap",
            "wh_vs_that_no_gap_long_distance",
            "wh_vs_that_with_gap",
            "wh_vs_that_with_gap_long_distance",
        ],
        "subject_verb_agreement": [
            "distractor_agreement_relational_noun",
            "distractor_agreement_relative_clause",
            "irregular_plural_subject_verb_agreement_1",
            "irregular_plural_subject_verb_agreement_2",
            "regular_plural_subject_verb_agreement_1",
            "regular_plural_subject_verb_agreement_2",
        ],
        "quantifiers": [
            "existential_there_quantifiers_1",
            "existential_there_quantifiers_2",
            "superlative_quantifiers_1",
            "superlative_quantifiers_2",
        ],
    },

    "rublimp": {
        "subject_predicate_agreement": [
            "clause_subj_predicate_agreement_gender",
            "clause_subj_predicate_agreement_number",
            "clause_subj_predicate_agreement_person",
            "genitive_subj_predicate_agreement_gender",
            "genitive_subj_predicate_agreement_number",
            "genitive_subj_predicate_agreement_person",
            "noun_subj_predicate_agreement_gender",
            "noun_subj_predicate_agreement_number",
            "noun_subj_predicate_agreement_person",
            "subj_predicate_agreement_gender_attractor",
            "subj_predicate_agreement_number_attractor",
        ],
        "floating_quantifier_agreement": [
            "floating_quantifier_agreement_case",
            "floating_quantifier_agreement_gender",
            "floating_quantifier_agreement_number",
        ],
        "np_agreement": [
            "np_agreement_case",
            "np_agreement_gender",
            "np_agreement_number",
        ],
        "reflexives": [
            "external_possessor",
        ],
        "anaphor_agreement": [
            "anaphor_agreement_gender",
            "anaphor_agreement_number",
        ],
        "negation": [
            "negative_concord",
            "negative_pronoun_to_indefinite",
            "indefinite_pronoun_to_negative",
        ],
        "government": [
            "verb_ins_object",
            "verb_acc_object",
            "verb_gen_object",
            "nominalization_case",
            "adposition_government",
        ],
        "argument_structure": [
            "transitive_verb",
            "transitive_verb_object",
            "transitive_verb_iobject",
            "transitive_verb_subject",
            "transitive_verb_passive",
        ],
        "aspect": [
            "change_duration_aspect",
            "change_repetition_aspect",
            "deontic_imperative_aspect",
        ],
        "tense": [
            "tense_marker",
            "single_verb_tense",
            "conj_verb_tense",
        ],
        "word_formation": [
            "change_verb_prefixes_order",
            "add_verb_prefix",
            "add_new_suffix",
        ],
        "word_inflection": [
            "change_declension_ending",
            "change_declension_ending_has_dep",
            "change_verb_conjugation",
        ],
    },

    "sling": {
        "alternative_question": [
            "haishi_ma",
        ],
        "anaphor_gender": [
            "self_male",
            "self_female",
            "pp_male",
            "pp_female",
        ],
        "anaphor_number": [
            "cl_self_male",
            "cl_self_female",
            "menself_male",
            "menself_female",
            "cl_men_self_male",
            "cl_men_self_female",
        ],
        "classifier_noun_agreement": [
            "dem_cl_swap",
            "cl_simple_noun",
            "cl_adj_simple_noun",
            "cl_comp_noun",
            "cl_adj_comp_noun",
            "cl_comp_noun_v2",
            "cl_adj_comp_noun_v2",
        ],
        "aspect": [
            "temporal_guo",
            "zai_guo",
            "temporal_le",
            "zai_le",
            "zai_no_le",
        ],
        "definiteness": [
            "definiteness_demonstrative",
            "definiteness_every",
        ],
        "polarity_item": [
            "any",
            "even_wh",
            "more_or_less",
        ],
        "relative_clause": [
            "rc_resumptive_noun",
            "rc_resumptive_pronoun",
        ],
        "wh_fronting": [
            "bare_wh",
            "mod_wh",
        ],
    },
}

FAMILIES = {
    "slavic": [
        "pol",
        "rus",
        "bul",
        "slv",
        "ukr",
        "hbs",
        "ces",
        "mkd",
        "slk",
        "bel",
        "orv",
        "hsb",
        "chu",
    ],
    "romance": [
        "ron",
        "spa",
        "ita",
        "por",
        "fra",
        "cat",
        "lat",
        "lij",
        "glg",
        "fro",
        "frm",
    ],
    "germanic": [
        "eng",
        "deu",
        "isl",
        "swe",
        "nld",
        "got",
        "fao",
        "nds",
    ],
    "baltic": [
        "lit",
        "lav",
    ],
    "celtic": [
        "bre",
        "gle",
        "cym",
    ],
    "indic": [
        "hin",
        "mar",
        "san",
        "xnr",
        "bho",
        "urd",
    ],
    "iranian": [
        "fas",
        "kmr",
    ],
    "hellenic": [
        "grc",
        "ell",
    ],
    "armenian": [
        "xcl",
        "hye",
        "hyw",
    ],
    "albanian": [
        "aln",
        "sqi",
    ],
    "anatolian": [
        "hit",
    ],
    "kartvelian": [
        "kat",
    ],
    "uralic": [
        "fin",
        "hun",
        "vep",
        "est",
        "myv",
        "krl",
        "kpv",
        "koi",
        "olo",
        "mdf",
        "sms",
        "sme",
    ],
    "afro-asiatic": [
        "arb",
        "heb",
        "amh",
        "hbo",
        "kxh",
        "egy",
    ],
    "turkic": [
        "tur",
        "uzb",
        "kaz",
        "kir",
        "sah",
        "ota",
        "uig",
    ],
    "mongolic": [
        "bua",
    ],
    "dravidian": [
        "tam",
    ],
    "northwest-caucasian": [
        "abk",
    ],
    "niger-congo": [
        "wol",
    ],
    "basque": [
        "eus",
    ],
    "uto-aztecan": [
        "azz",
        "nhi",
    ],
    "mayan": [
        "quc",
        "ttc",
    ],
    "arawakan": [
        "apu",
    ],
    "macro-je": [
        "bor",
    ],
    "tupi-guarani": [
        "yrl",
    ],
    "uncategorized": [
        "xpg",
    ]
}
